import { useEffect, useState } from 'react';

export default function StoreSuggest({ familySize, annualIncome }) {
    const [recommendation, setRecommendation] = useState('');

    useEffect(() => {
        const fetchRecommendation = async () => {
            const systemPrompt = 'You are an expert in store recommendations based on spending behavior. Recommend stores to customers based on their family size and income. Be conversational, professional, helpful, friendly, and provide a personalized experience. DO NOT mention their family size, income, nor category in the response. Do not reveal that you have any personal information of the user. Format your response as a single conversational plaintext paragraph.';
            // console.log(familySize, annualIncome);
            const userPrompt = `Recommend stores for a user with family size of ${familySize} and income of ${annualIncome} from the following list. Only pick stores with properly formatted names.

If Family Size > 1, categorize as Family or Frugal Family based on income.
If Family Size = 1, categorize as one of the Spenders based on income.
Income Ranges:

$40,000 - $60,000: Frugal Family
$70,000 - $100,000: Family
$80,000 - $100,000: Sensible Spenders
$120,000 - $150,000: Urban Spenders
$150,000 - $200,000: Affluent Spenders


APCOA
NYA
TAKEAWAY.JE
MANCHESTER.GOV.UK
MAPAC GROUP
ASOS.COM
DRIVER & VEHICLE LICENSING AGENCY
JAGUARS TICKETS
TFL-TICKET PURCHASE
PIZZA HUT
SAINSBURY'S
APPLE.COM/BILL
ITUNES MUSIC STORE
WM MORRISON
AMPAY
AGE UK
FREDDIES FLOWERS
AIRBNB 
AIRBNB GLOBAL NETWORK
SUTTON SPORTS DIRECT
AMAZON.CO.UK
AMAZON.COM
PRIME VIDEO CHANNELS
PAYPAL
NYA BP
NETFLIX
TEXACO
AUDIBLE INC
AUDIBLE UK
AMAZON MUSIC
AMZN MKTP UK
AMZNMKTPLACE
AMAZON
AMAZON PRIME
AMZN MKTP US
WAKEHURST
EMBER INNS
THE REDS MERCHANDISE
SUNDAY FEGO   BANSTEAD
THE LEMON TREE LIMITED
THE LEMON TREE
COSTA COFFEE
SQUARE INC
MARKS & SPENCER
CAFFE NERO
WAITROSE
CAFFE NERO BANSTEAD
MCDONALDS
DEARNE VALLEY FARM
KENTUCKY FRIED CHICKEN
COMPANY SHOP LTD
NSL RB KINGSTON (E)
EPOCH.COM
SP SOUNDCORE UK
SHOPIFY.COM
SUMUP
WWW.CARLUCCIOS.COM
CARLUCCIO'S
JD SPORTS
BAIT & TACKLE SHOP
BRITISH GAS
ASDA
STAGECOACH
COBBLESTONES
STROKE ASSOCIATION
EVENT MOBILE CATERING
EVENT MOBILE CATERING LTD
CABCARD
TESCO
LATINO'S
SUBWAY
MEDWAY COUNCIL ON STRE
MEDWAY SPORT
BARNARDOS
LIDL
COHENS CHEMIST
LUNCH BOX
CHESSINGTON GARDEN CNTRE
BARWELL KEBAB HSE
BARWELL KEBAB HOUSE
CHESTER ZOO
CHESTER ZOO FOOD OUTLET
ZETTLE_
IZETTLE
WHSMITH
TAPORI
THE CO-OPERATIVE UK
WWW.BLUELIGHTCARD.CO.U
BLUE LIGHT CARD
CARD FACTORY
BOOTS THE CHEMIST
ALDI SUPERMARKET
MUNCH @ COUGHLANS
PEMBROKE - COULSDO
J H LORIMER
PIZZA EXPRESS
SMITH & WESTERN TILGATE
SMITH WESTERN TILGA
CRAWLEY BOROUGH COUNCIL
SOUTHERN COUNTIES CRAWLEY
SOUTHERN COUNTIES ICE CRE
THE WALLED GARDEN CAFE
CHATWINS VIC ST CL
CHESHIRE EAST COUNCIL
CREWE CAR PARK
PUMPKIN CAFE
ELDORADO RESORT CASINO
DARENT VALLEY HOSPITAL
SHELL
LLOYDS PHARMACY
TACO BELL
DARTFORD TYRE & ACCESS
KENT CURRY
LEVAILLANTS LIMITED
POST OFFICE UK
M & S SIMPLY FOOD
PREMIER PARKING SO
PREMIER PARK LTD
EPSOM/GEN HOSP PH
EPSOM COSTA
HORTON PRACTICE
PIZZERIUM
CLINTON CARDS
EPSOM & EWELL BRGH COU
BP WOODCOTE S/SERVE
BP
THE ROYAL AIR FORCE CHARITABLE
TITCHFIELD FESTIVAL THEATRE
SMOL LIMITED
SMOL
METAPAY NATIONALMSSOCI
GREGGS
WELCOME BREAK
GOOGLE GOOGLE STORAGE
GOOGLE YOUTUBEPREMIUM 
GOOGLE
GODSTONE FARM
GODSTONE FARM LIMITED
SHOWCASE CDL BLUEWATER
APPLE STORE R113
APPLE STORE
COTE BRASSERIE
C?TE BLUEWATER
VISION EXPRESS
H M HENNES & MAURITZ
STARBUCKS
FREEMANS EVENT PARTNERS C
FREEMANSEVENTPARTNERS
PAYBYPHONE RE CHESHIRE EA
PAYBYPHONE
PAYBYPHONE RE SWINDON BOR
GRAYSONS@ WAKEHURST
GRAYSONS AT WAKEHURST
NORTHERN RAIL
BRIDGE BAR
UBER  EATS
UBER EATS
STARLANE FUEL SERVICES
HOUNSLOW HEATH GOLF CE
HOUNSLOW HEATH GOLF CENTR
WWW.RHS.ORG.UK
WWW.CADGANHALL.COM
WWW.SOHOTHEATRE.TICKET
STEAK AND COMPANY
THE RAJ
THE FOX INN
ROBINSONS (PHILIPPINES)
BUY SOUTH AFRICA KINGS
SUPERDRUG
BOATERS
KINGSTON UPON THAMES PRZYM ECOMM
RINGGO
LEICESTER SQUARE THEAT
LEICESTER SQUARE
HARBOUR PARK
WILLIAMS AND SONS WEST SU
HARVESTER
FEVER UK
DIBS.LIVE
UBER
FEVER UK STAND UP PAD
JG GREAT ORMOND STREE
SQ 
PYD
PCS
ICC MISSIONS
MOONPIG
MOONPIG.COM
JUSTGIVING
WAGAMAMA
COLLECTION POT LIMITED
COLLECTION POT
KING OF FALAFEL
SPOTIFY
SHEBA RESTAURANT
SHEBA
ESSO
GETIR
FAST BREAK
FAST BREAK KOZZY CAFE
KLARNA
OLE & STEEN - RICHM
O2R LTD
THE GEORGE
GEORGE
YUM BOWL
YUMBOWL
DISCOVERY+ STANDARD
SPOTIFY UK
EBAY
DELIVEROO
SIMPLYCOOK.COM
SP GRIPIX
ODEON CINEMAS
HACKNEY EMPIRE TRADING LI
HACKNEY EMPIRE TRADING
ACADEMY VIDEO
GAUCHO SLOANE
ARGENTINE STEAK RESTAURANT
C?TE BARBICAN
S W LONDON ICE CREAM
BELLAMY ICES
HOA SEN
HOA SEN LTD
KIOSK
LS GREENHITHE BLUEWATE
MARYLEBONE CRICKET CLUB
A FUORVITO & SONS
MCC HOSPITALITY
SP LONDON COLISEUM S
JUST EAT
TST-STEAK AND COMPANY
CITY OF LONDON CORPORATION
TONKOTSU
EVENTS DEEP BLUE
KUTIR RESTAURANT
CROWN
PEOPLES SUPERMARKE
CINEWORLD
93 FEET EAST
TTG
CADOGAN HALL
THE WELLINGTON HOTEL
BP OAKTREE CONNECT
MANCHESTER CITY COUNCIL
MAN STATION TVM
BRAISWICK PHOTOGRAPHIC CO
BRAISWICK PHOTOGRAPHIC CO LTD
ROSE CROWN
MILL VIEW FISHING TACK
1752
DOMINO'S PIZZA
HOME BARGAINS
TASTE FOR LIFE
ROSIE S BEAUTY
T.J.MORRIS
SNUGBURYS ICE CREAM LT
THE WORKS
TRUE PHYSIO LTD
ROSIE
MALISTA AROMA LTD
CAFFE NERO NANTWICH
EVERYBODY HEALTH & LEISURE E9B15C3C-08FC-4DF8--5B6A6660B26F_22575
WHITE RIBBON BOUTIQUE NAN
FIRST STOP OFF LICENCE
CHATWINS SQUARE
ST LUKES HOSPICE TAVIS
VAPE & PHONES
WELL
1ST STOP
OPTIONS MANAGEMENT LTD
SHOWCASE CINEMAS
ANSCO ARENA
YOURS
BELFRY SC
REDHILL
RBBC-PARKING
LYONS ROBIN HOOD HOLIDAY
LYONS ROBIN HOOD HOLIDAY PARK TOY SHOP
GREENS SUPERMARKET
MILOS DINER AND TAKEAW
SPAR
NOTONTHEHIGHSTREET.COM
CHUNKYS AIRSTREAM LTD
LONDON CATERING SERVICES
TOBY CARVERY BASIL
WHITBY'S
WHITBY'S ROTHERHAM
SANDBACH UNITED
SCRIBD
D & J ANGLING
STATION CAFE CHAPELTOWN
COSTCO WHOLESALE
JOHN CRAWSHAW BUTCHERS
BERES
S BERES AND SON
BROWNS RESTAURANT & BAR
FIRST SOUTH YORKSHIRE
ROSES THE BAKERS
SPORTS DIRECT
SPORTSDIRECT.COM
PAYGPYMT
PHOENIX LLC
THE ANTELOPE
HARTS BOATYARD
ARTISAN BAKERY
THE  ARTISAN BAKERY
ALLIGATOR PEAR
SUTTON SPORTS PARK
H. SAMUEL
PRIMARK
NEXT
WENDYS
ST NICHOLAS SHOPPING CENT
NEW LOOK
CLAIRES BOUTIQUE
PAYPOINT
MIDSHIRE SIGNATURE SER
TFL-CONTACTLESS TRAVEL
MEDITERRANEAN SUPERMARKET
THE PRINCE ALBERT - FULLERS PUBS
LONDON BOROUGHS
SQUIRES GARDEN CENTRE
SUSSEX
SANTA POD RACEWAY
ROYAL OAK W/M
ROYAL OAK
THE BOATMAN
BOATMAN
ST LUKES CHESHIRE HOSPITAL
WISHTENDER
WISHTENDER.COM
NORTH NOTTS FISHING & SHOOTING
THE BLUEBIRD CAFE LIMITED
THE BLUEBIRD CAFE LIMI
ATG TICKETS
EURO CAR PARKS
`;

            try {
                const response = await fetch('/api/gpt4', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({
                        system_prompt: systemPrompt,
                        user_prompt: userPrompt,
                    }),
                });

                const data = await response.json();
                setRecommendation(data.response);
            } catch (error) {
                console.error('Error fetching recommendation:', error);
            }
        };

        fetchRecommendation();
    }, [familySize, annualIncome]);

    return (
        <div>
            <h2>Store Recommendations</h2>
            {recommendation ? <p>{recommendation}</p> : <p>Loading...</p>}
        </div>
    );
}
